apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rider-service-pdb
  namespace: default
  labels:
    app.kubernetes.io/name: rider-service
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: rider-service
