apiVersion: v1
kind: ConfigMap
metadata:
  name: region-config
  namespace: rideshare-prod
data:
  CLUSTER_ROLE: "secondary"
  ENVIRONMENT: "production"
  DB_ENDPOINT: "rideshare-postgres.curogmywuw25.us-east-1.rds.amazonaws.com"
  REDIS_ENDPOINT: "clean-mustang-37120.upstash.io"
  FEATURE_FLAG_MULTI_REGION: "true"
