apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: driver-service-secrets
    namespace: rideshare-app
spec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: driver-service-secrets
    data:
      - secretKey: DATABASE_URL
        remoteRef:
          key: light/driver-service
          property: DATABASE_URL
      - secretKey: JWT_SECRET
        remoteRef:
          key: light/driver-service
          property: JWT_SECRET
      - secretKey: REDIS_HOST
        remoteRef:
          key: light/driver-service
          property: REDIS_HOST
      - secretKey: REDIS_PORT
        remoteRef:
          key: light/driver-service
          property: REDIS_PORT
      - secretKey: REDIS_PASSWORD
        remoteRef:
          key: light/driver-service
          property: REDIS_PASSWORD
      - secretKey: REDIS_URL
        remoteRef:
          key: light/driver-service
          property: REDIS_URL
