apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: trip-service-pdb
  namespace: default
  labels:
    app.kubernetes.io/name: trip-service
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: trip-service
