apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: email-service-secrets
    namespace: rideshare-app
spec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: email-service-secrets
    data:
      - secretKey: AZURE_EMAIL_CONNECTION_STRING
        remoteRef:
          key: rideshare/email-service
          property: AZURE_EMAIL_CONNECTION_STRING